apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "ecr-cleaner.fullname" . }}
  labels:
    {{- include "ecr-cleaner.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.schedule }}"
  jobTemplate:
    metadata:
      labels:
        {{- include "ecr-cleaner.selectorLabels" . | nindent 8 }}
    spec:
      template:
        metadata:
          labels:
            {{- include "ecr-cleaner.selectorLabels" . | nindent 12 }}
          {{- if .Values.podAnnotations }}
          annotations:
            {{ toYaml .Values.podAnnotations | nindent 12 }}
          {{- end }}
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "ecr-cleaner.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          containers:
          - name: {{ .Chart.Name }}
            args:
            {{- if .Values.config.days }}
            - "--days"
            - "{{ .Values.config.days}}"
            {{- end }}
            {{- if .Values.config.debug }}
            - "--debug"
            {{- end }}
            {{- if .Values.config.dryRun }}
            - "--dry-run"
            {{- end }}
            {{- if .Values.config.force }}
            - "--force"
            {{- end }}
            {{- if .Values.config.noSemver }}
            - "--no-semver"
            {{- end }}
            {{- if .Values.config.region }}
            - "--region"
            - "{{ .Values.config.region}}"
            {{- end }}
            {{- if .Values.config.repo }}
            - "--repo"
            - "{{ .Values.config.repo}}"
            {{- end }}
            securityContext:
              {{- toYaml .Values.securityContext | nindent 14 }}
            image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            resources:
              {{- toYaml .Values.resources | nindent 14 }}
          restartPolicy: Never
        {{- with .Values.nodeSelector }}
        nodeSelector:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- with .Values.affinity }}
        affinity:
          {{- toYaml . | nindent 10 }}
      {{- end }}
      {{- with .Values.tolerations }}
        tolerations:
          {{- toYaml . | nindent 10 }}
      {{- end }}
